name: Mon premier workflow
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  say-bye:
    needs: ["say-hello"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "bonjour" > test.txt
      - uses: actions/checkout@v4
      - run: ls -la
