name: Mon premier workflow
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - run: ls -l
  say-bye:
    needs: ["say-hello"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye World!"
